# Generated by Django 4.2.2 on 2023-06-11 08:24

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=100, unique='True')),
                ('pdf_file', models.FileField(upload_to=app.models.pdf_file_model.user_directory_path)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='None', max_length=250)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pdf_file_model')),
            ],
        ),
    ]
