# Generated by Django 4.2.2 on 2023-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinvitationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_file_model',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
