# Generated by Django 4.2.2 on 2023-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pdf_file_model_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf_file_model',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
